#!/usr/bin/env python3
"""
SiriBot Quick Setup - User-friendly setup for non-technical users.
This provides a simple GUI installer experience.
"""

import subprocess
from pathlib import Path
import importlib.util
import shutil


def check_requirements():
    """Check if all requirements are met."""
    missing = []

    if not shutil.which("xcodebuild"):
        missing.append("Xcode (install from Mac App Store)")

    if not importlib.util.find_spec("ollama"):
        missing.append("Ollama (run: brew install ollama)")

    return missing


def install_ollama():
    """Guide user to install Ollama."""
    print("""
╔══════════════════════════════════════════════════════════════╗
║                    Installing Ollama                         ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  Ollama is required for local AI. Run this command:          ║
║                                                              ║
║  brew install ollama                                         ║
║                                                              ║
║  Then download a model:                                      ║
║                                                              ║
║  ollama pull llama3.2                                        ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
""")


def create_config():
    """Create default configuration."""
    config_dir = Path.home() / ".siribot"
    config_dir.mkdir(exist_ok=True)

    config_path = config_dir / "config.yaml"

    if not config_path.exists():
        default_config = """# SiriBot Configuration
# Generated by Quick Setup

app:
  name: "SiriBot"
  version: "1.0.0"
  log_level: "INFO"

model:
  provider: "ollama"
  ollama:
    base_url: "http://localhost:11434"
    model: "llama3.2"
    temperature: 0.7
    max_tokens: 2048

voice:
  input:
    engine: "whisper"
    model: "base"
  output:
    engine: "pyttsx3"
    rate: 200
    volume: 1.0

agent:
  max_iterations: 10
  confirmation_required:
    - "delete"
    - "rm"
  timeout_seconds: 300

memory:
  db_path: "~/.siribot/memory.db"

safety:
  allow_shell_commands: true
  allow_file_operations: true

sync:
  enabled: false

integrations:
  calendar: true
  notes: true
  reminders: true
"""
        config_path.write_text(default_config)
        print(f"Configuration created at: {config_path}")

    return config_path


def download_model():
    """Download default AI model."""
    print("""
╔══════════════════════════════════════════════════════════════╗
║                    Downloading AI Model                       ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  To download the recommended model (llama3.2), run:           ║
║                                                              ║
║  ollama pull llama3.2                                        ║
║                                                              ║
║  Other options:                                              ║
║  - ollama pull mistral        (smaller, faster)              ║
║  - ollama pull codellama      (better for coding)             ║
║  - ollama pull mixtral        (larger, more capable)         ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
""")


def main():
    print("""
╔══════════════════════════════════════════════════════════════╗
║                        SiriBot Setup                          ║
║                   Your AI Assistant for Mac                   ║
╠══════════════════════════════════════════════════════════════╣
""")

    # Check for XcodeGen
    if not shutil.which("xcodegen"):
        print("Installing XcodeGen...")
        subprocess.run(["brew", "install", "xcodegen"])

    # Create config
    create_config()

    # Check Ollama
    if importlib.util.find_spec("ollama"):
        print("✓ Ollama is installed")
    else:
        install_ollama()

    print("""
╔══════════════════════════════════════════════════════════════╗
║                      Setup Complete!                          ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  To build SiriBot:                                           ║
║  1. cd macos/SiriBot                                         ║
║  2. xcodegen generate                                        ║
║  3. xcodebuild -scheme SiriBot -configuration Release build   ║
║                                                              ║
║  Or use the build script:                                     ║
║  ./setup/build.sh                                            ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
""")


if __name__ == "__main__":
    main()
